version: '3.8'

services:
  faqup-bot:
    container_name: faqup-bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - default-network

networks:
  default-network:
    driver: bridge